### PR TITLE
Single observation table

### PR DESCRIPTION
**Pull request by peterdesmet**
_Note: ~this is an experiment.~ This is a proposal for change. @kbubnicki and I are working on Camtrap DP this week, and it got me thinking if it would be possible to find a more elegant solution than the current split `media-observations` / `event-observations` table._

## Rationale

#203 split the observations in two tables: one for media-based observations and one for event-based observations. The main goal was clear communication (got event-based observations? Add them here). However:
- The conditional approach (event-observations, media-observations and/or both) makes it difficult for implementations that want to load the observations (e.g. camtraptor). Which ones should be loaded?
- It made it difficult to talk/refer to `observations`
- It is not possible to indicate events that are different the ones dictated by `eventID`. For example a track of an animal moving in 3 consecutive images that is part of a bigger event, a selection of a video.
- A media file could is restricted to be part of a single event only.

## What

This pull requests suggests to combine the observations in a single table again. **Events are defined by a `start/end` duration in the observations.** Here's a preview (see https://github.com/tdwg/camtrap-dp/blob/single_obs/example/observations.csv for a full example):

observationID | deploymentID | mediaID | start | end | scientificName | count
--- | --- | --- | --- | --- | --- | ---
obs1 | dep2 | med1 | 2020-08-02T05:00:14Z | 2020-08-02T05:00:14Z | Anas platyrhynchos | 3
obs2 | dep2 | med2 | 2020-08-02T05:00:15Z | 2020-08-02T05:00:15Z | Anas platyrhynchos | 3
obs3 | dep2 | med3 | 2020-08-02T05:00:15Z | 2020-08-02T05:00:15Z | Anas platyrhynchos | 3
obs4 | dep2 | med4 | 2020-08-02T05:00:16Z | 2020-08-02T05:00:16Z | Anas platyrhynchos | 3
obs5 | dep2 | med5 | 2020-08-02T05:00:16Z | 2020-08-02T05:00:16Z | Anas platyrhynchos | 3
obs6 | dep2 | med6 | 2020-08-02T05:00:17Z | 2020-08-02T05:00:17Z | Anas platyrhynchos | 4
obs7 | dep2 | med7 | 2020-08-02T05:00:18Z | 2020-08-02T05:00:18Z | Anas platyrhynchos | 4
obs8 | dep2 | med8 | 2020-08-02T05:00:18Z | 2020-08-02T05:00:18Z | Anas platyrhynchos | 4
obs9 | dep2 | med9 | 2020-08-02T05:00:19Z | 2020-08-02T05:00:19Z | Anas platyrhynchos | 4
obs10 | dep2 | med10 | 2020-08-02T05:00:19Z | 2020-08-02T05:00:19Z | Anas platyrhynchos | 4
obs11 | dep2 | NULL | 2020-08-02T05:00:14Z | 2020-08-02T05:00:19Z | Anas platyrhynchos | 5

- Observations have a `start` and `end` timestamp. That constitutes the event. There are no `eventID`s.
- Observations can be linked to media by selecting all media with a `timestamp` that falls within the `start-end` of the observation. A `deploymentID` is needed to restrict this join, because it is possible that cameras deployed at the same time (different deployments) recorded media at the same time. This `deploymentID` is also very convenient for joining observations directly to deployments (something we lost in the current split observations approach).
- Cameras typically don't record milliseconds in `timestamp`, which can result in consecutive media having the same timestamp. `deploymentID` and `timestamp` is thus not enough to uniquely link a media-based observation to a media. That is why `mediaID` is added. This field is populated for media-based observations and left empty when multiple media were considered.
- Observations `obs1` to `obs10` are media-based observations. Notice a direct link with the `mediaID` and `start=end`
- Observation `obs11` is event-based. Notice there is no direct link to `mediaID` and the `start/end` duration constitutes a longer duration. It is possible to indicate the entire `count` for that duration (here 5, even though in single images not more than 4 were seen).
- `start` and `end` are required fields. For a media-based observation, it has the same values.
- `start/end` allows to indicate subsets of a video media file (#309) and it is also still possible to indicate `boundingBox` to further zoom in on a media-based observation.

## How is this different from the initial model in 0.1.6?

See the [0.1.6 observations table](https://github.com/tdwg/camtrap-dp/blob/0.1.7/example/observations.csv)

- 0.1.6 required a `sequence/eventID` for all observations, even for media-based observations. This proposal does not have `eventID`, only durations.
- 0.1.6 demanded to either have media or event based observations, not both (with `classificationLevel`). This proposal allows both.
- 0.1.6 had conditional joins with the media table (either on `sequenceID` or on `mediaID`). This proposal allows to join media-based observations directly with media on `mediaID`, event-based observations can be joined with media if necessary on `deploymentID, start/end`.

### Identify media-based vs event-based observations?

Filter on `mediaID != NULL` for media-based observations and `is.null(mediaID)` for event-based observations.

### Link media-based observations with media?

Join `observations` and `media` tables on `mediaID`

### Link event-based obs with their media?

Join `media` and `observations` on `deployment` and `timestamp` between `start` and `end`

```{r}
media %>%
  select(mediaID, deploymentID, timestamp, filePath) %>%
  full_join(
    # Join with observations without mediaID
    filter(observations, is.na(mediaID)),
    # Join on deploymentID and timestamp between start and end
    join_by(deploymentID, between(timestamp, start, end))
  )
```

### Have permanent identifiers for events?

That is not possible, unless we introduce an optional `eventID` convenience field, which is probably better called `sequenceID`.

### Get grouping identifiers for event-based observations?

Concatenate `deploymentID,start,end` to create identifiers for events. It will group all observations within those events.

### Create your own events from media-based observations?

```{r}
# Bucket observations per scientific name and hour and get maximum group size
observations %>%
  # For a large samples it might not even be necessary to filter out event obs
  # filter(!is.na(mediaID)) %>%
  filter(!is.na(scientificName)) %>%
  mutate(startMinute = lubridate::round_date(start, unit = "hour")) %>%
  mutate(eventID = paste(deploymentID, startMinute)) %>%
  group_by(
    eventID,
    scientificName
  ) %>%
  summarize(
    maxCount = max(count)
  )
```

### Create a track for an individual and calculate the speed

Sort on `start` and find consecutive observations of the same `individualID`. Calculate speed based on `start/end` duration.

### Link media-based observations with corresponding event-based observations

Note that this is not straightforward in the current `event-obs`/`media-obs` approach: you can walk up from a `media-obs` to a `media`, see the corresponding `eventID` and at least find a collection of observations linked to that `eventID`. You would have to filter on `scientificName`, `sex`, `lifeStage`, etc. to find the exact corresponding observation.

Something similar would need to be done here, where you select media-based observations that fall within the `start/end` of event based observations and have the same `scientificName`, `sex`, `lifeStage`.

### CODE REVIEW

**Comment by peterdesmet** [comment]
@tucotuco @kbubnicki @danstowell @timrobertson100 @yliefting @damianooldoni @pietrH @jimcasaer your feedback on this proposal would be much appreciated.

**Comment by danstowell** [comment]
Broadly, this seems OK to me. I always preferred non-split versions, so IMHO this is an improvement. What I see here seems compatible (interchangeable) with the data format we came up with in [the Arise schema](https://www.arise-biodiversity.nl/post/an-api-for-ai-species-recognition) too. A couple of questions:

1. Why are `start` and `end` required fields even for a media-level observation, when the timestamp is already recorded in `media.csv`? Wouldn't `NULL` also be a direct way to indicate a media-level observation?
2. "It is also still possible to indicate `boundingBox`" - I don't see that column in the example files, so it's not clear how.

**Comment by peterdesmet** [comment]
Thanks @danstowell 

1. Since `start` and `end` are really necessary for event-level observations and fairly easy to provide for media-level observations, I think it makes sense to make them required to help validation.
2. Indeed, a bounding box is not indicated yet in the examples, that will be tackled as part of #219. I'll add a comment there.

**Comment by timrobertson100** [comment]
You asked for comment but I'm afraid I don't know the domain well enough to have meaningful input (don't know the tools or the typical questions asked etc). I find it is clearly outlined though, so would know how to consume it and I like the example-based approach.

**Comment by jimcasaer** [comment]
Although I understood from Peter yesterday that the type of observation (event-based / media-based) can be deduced from the data I think that it would make life easier for some of us if a column was added to the table indicating the "observation type"

**Comment by kbubnicki** [comment]
To  be more explicit in guiding (human) users ,1) which observation is event-based and which is media-based (in a case where you have both) and 2) which media belong to a given event (without running more complex joins as described above by @peterdesmet ), I would suggest to add the following two fields:

1. **observationLevel** with two levels: `media` and `event`
2. **eventID**

| observationID | deploymentID | mediaID | eventID | observationLevel | start                | end                  | scientificName     | count |
|---------------|--------------|---------|---------|------------------|----------------------|----------------------|--------------------|-------|
| obs1          | dep2         | med1    | event1  | media            | 2020-08-02T05:00:14Z | 2020-08-02T05:00:14Z | Anas platyrhynchos |     3 |
| obs2          | dep2         | med2    | event1  | media            | 2020-08-02T05:00:15Z | 2020-08-02T05:00:15Z | Anas platyrhynchos |     3 |
| obs3          | dep2         | med3    | event1  | media            | 2020-08-02T05:00:15Z | 2020-08-02T05:00:15Z | Anas platyrhynchos |     3 |
| obs4          | dep2         | med4    | event1  | media            | 2020-08-02T05:00:16Z | 2020-08-02T05:00:16Z | Anas platyrhynchos |     3 |
| obs5          | dep2         | med5    | event1  | media            | 2020-08-02T05:00:16Z | 2020-08-02T05:00:16Z | Anas platyrhynchos |     3 |
| obs6          | dep2         | med6    | event1  | media            | 2020-08-02T05:00:17Z | 2020-08-02T05:00:17Z | Anas platyrhynchos |     4 |
| obs7          | dep2         | med7    | event1  | media            | 2020-08-02T05:00:18Z | 2020-08-02T05:00:18Z | Anas platyrhynchos |     4 |
| obs8          | dep2         | med8    | event1  | media            | 2020-08-02T05:00:18Z | 2020-08-02T05:00:18Z | Anas platyrhynchos |     4 |
| obs9          | dep2         | med9    | event1  | media            | 2020-08-02T05:00:19Z | 2020-08-02T05:00:19Z | Anas platyrhynchos |     4 |
| obs10         | dep2         | med10   | event1  | media            | 2020-08-02T05:00:19Z | 2020-08-02T05:00:19Z | Anas platyrhynchos |     4 |
| obs11         | dep2         | NULL    | event1  | event            | 2020-08-02T05:00:14Z | 2020-08-02T05:00:19Z | Anas platyrhynchos |     5 |

**Comment by Tim-Hofmeester** [comment]
I think this solution would work quite well both for image and for sequence based classifications, especially with the additional fields suggested by @kbubnicki. 

I am just thinking of one edge case that I think it would work for, but am not 100% sure. What if you have a sequence based classification of a sequence that includes two species, but one of the two species only occurs in the first half of the sequence. I guess you would then have two rows, one for each species, and both rows contain the same start, but different end times. Correct?

@peterdesmet : is the example of the ducks above indeed the way you envision this table being used? That data that is classified per image is basically added to the table twice, once per image, and once for the whole sequence (to get the correct group size)?

**Comment by peterdesmet** [comment]
@Tim-Hofmeester 

> I am just thinking of one edge case that I think it would work for, but am not 100% sure. What if you have a sequence based classification of a sequence that includes two species, but one of the two species only occurs in the first half of the sequence. I guess you would then have two rows, one for each species, and both rows contain the same start, but different end times. Correct?

Correct

> is the example of the ducks above indeed the way you envision this table being used? That data that is classified per image is basically added to the table twice, once per image, and once for the whole sequence (to get the correct group size)?

Correct, it is a rather verbose example where data were classified at media level, but an extra event/sequence level observation is added to be able to express sequence-level proporties such as correct group size.

**Comment by MarcusRowcliffe** [comment]
This proposal works for all use cases I can think of. 

On @kbubnicki 's suggestion, I agree it would make things a little easier (for me at least) to have `eventID` and `observationLevel` fields, but would be (almost) equally happy to work with joins / filters to effectively create these.

I'm just unclear on the use and meaning of `eventID` versus `individualID` versus `sequenceID` here:

@peterdesmet, you suggested potentially adding "`eventID` ... probably better called `sequenceID`". Assuming we will keep the current Agouti process which creates and labels sequences based on a minimum time gap, it seems to me better to reserve `sequenceID` to denote these gap-defined media groups, and use `eventID` to denote (potentially) sub-sequence media groups (which can be defined flexibly to fulfill specific use cases).

@peterdesmet, you also suggested using `individualID` to group media for speed calculation (a specific use case), but it seems to me that an event-based grouping, based on `eventID`, is already fine for this. If that's right, I think `individualID` could then be reserved to denote genuine individual identities in marked animal studies (which would be ideal I think).

**Comment by peterdesmet** [comment]
Thanks for your feedback @MarcusRowcliffe. I discussed this with @kbubnicki

- We agree it would be useful if Agouti can express its sequence identifier in Camtrap DP, its a useful reference
- We agree it would be useful to link related observations together
- We think that adding a `sequenceID` in addition to an `eventID` will complicate things.

Let's say a fox makes two passages: on media 1 and 2, and media 5 and 6. Another fox spoils the fun, so we clearly identify it as individualID `A`. We also want to add the sequence identifier from Agouti.

## Option 1

With the current structure, my recommendation would be to bind the passages and their media observations with the individualID (`A`). **The advantage is that you are using `individualID` for the intended purpose: to track individuals across observations, even if very shortly.** The Agouti sequence identifiers _could_ be put in eventID, even if they don't strictly align with the start/end.

scientificName | mediaID | start | end | individualID | eventID
-- | -- | -- | -- | -- | --
fox | 1 | T1 | T1 | A | seq1
fox | 2 | T2 | T2 | A | seq1
another fox | 2 | T2 | T2 |   | seq1
blank | 3 | T3 | T3 |   | seq1
blank | 4 | T4 | T4 |   | seq1
fox | 5 | T5 | T5 | A | seq1
fox | 6 | T6 | T6 | A | seq1
fox | NULL | T1 | T2 | A | seq1
fox | NULL | T5 | T6 | A | seq1

## Option 2

Another option (as you suggest) would be to put the passages in `eventID`. Rather than adding an extra `sequenceID`, the Agouti identifiers could be put in the existing field `observationTags`. **The advantage here is that the eventID align with the duration, but I'm not sure it's necessary to have that requirement**.

scientificName | mediaID | start | end | eventID | observationTags
-- | -- | -- | -- | -- | --
fox | 1 | T1 | T1 | passage1 | sequence:seq1
fox | 2 | T2 | T2 | passage1 | sequence:seq1
another fox | 2 | T2 | T2 |   | sequence:seq1
blank | 3 | T3 | T3 |   | sequence:seq1
blank | 4 | T4 | T4 |   | sequence:seq1
fox | 5 | T5 | T5 | passage2 | sequence:seq1
fox | 6 | T6 | T6 | passage2 | sequence:seq1
fox | NULL | T1 | T2 | passage1 | sequence:seq1
fox | NULL | T5 | T6 | passage2 | sequence:seq1

## Option 3

The reverse of option 2: put the Agouti identifiers in `eventID`, but the passages in `observationTags`:

scientificName | mediaID | start | end | eventID | observationTags
-- | -- | -- | -- | -- | --
fox | 1 | T1 | T1 | seq1 | passage:passage1
fox | 2 | T2 | T2 | seq1 | passage:passage1
another fox | 2 | T2 | T2 | seq1 |  
blank | 3 | T3 | T3 | seq1 |  
blank | 4 | T4 | T4 | seq1 |  
fox | 5 | T5 | T5 | seq1 | passage:passage2
fox | 6 | T6 | T6 | seq1 | passage:passage2
fox | NULL | T1 | T2 | seq1 | passage:passage1
fox | NULL | T5 | T6 | seq1 | passage:passage2

## Option 4

Don't have a dedicated `eventID` field that could conflict with the duration and have any custom grouping in `observationTags`:

scientificName | mediaID | start | end | observationTags
-- | -- | -- | -- | --
fox | 1 | T1 | T1 | sequence:seq1 \\| passage:passage1
fox | 2 | T2 | T2 | sequence:seq1 \\| passage:passage1
another fox | 2 | T2 | T2 | sequence:seq1
blank | 3 | T3 | T3 | sequence:seq1
blank | 4 | T4 | T4 | sequence:seq1
fox | 5 | T5 | T5 | sequence:seq1 \\| passage:passage2
fox | 6 | T6 | T6 | sequence:seq1 \\| passage:passage2
fox | NULL | T1 | T2 | sequence:seq1 \\| passage:passage1
fox | NULL | T5 | T6 | sequence:seq1 \\| passage:passage2

---

Our opinion is that the current structure would meet the passage use case requirements, with a preference to Option 1. We could even consider to drop `eventID` altogether and refer to `observationTags` if people want to group observations as they want.

**Comment by tucotuco** [comment]
A little late in the conversation, and talk has turned to details, but I support the single table approach for observations over the split one.

**Comment by peterdesmet** [comment]
@MarcusRowcliffe

> Option 1 doesn't uniquely identify passages, so I can't see how to use that for REM / distance sampling purposes.

You would need to use `individualID` in combination with `start`/`end` to uniquely identify passages.

> but I'm feeling more and more strongly that it would be best reserved for permanent individual identification, not used to identify passages.

I understand and as shown in option 2, 3, 4 there are other options to support this use case. To me that is the most important conclusion to draw: the proposed model supports this use case. I think we'll have to work with actual Agouti exports to test the best approach.

> If passage identifiers are available then I don't see the need for start and end fields in the observations table - maybe they could be tidied up?

The `start` and `end` fields are key to this proposal, as they form the main way to indicate events. Those fields are required. `eventID`s (in case you have/need them) are optional.

**Comment by peterdesmet** [comment]
It looks like we have consensus that this proposal (single table approach) is better than the split table approach (v0.6). All uses cases that were raised can be implemented. Thanks for the support!

**Comment by peterdesmet** [comment]
Summary of the changes:

## Package

- Removes `eventInterval`, since events can be expressed in multiple ways (#317).
- Introduces `observationLevel`, which can be `media`, `event` or `[event, media]` (similar to `captureMethod`)

## Deployments

- Renames `start`/`end` to `deploymentStart`/`deploymentEnd` to make it consistent with `eventStart`/`eventEnd` (#321).

## Media

- Removes `eventID`

## Observations

- Single table for observations.
- Introduces new field `eventStart`, `eventEnd`, `observationLevel` to observation table.
- Adds `deploymentID` back to the observation table, necessary to restrict joins to the media table and helpful for directly joining observations with deployments.
- Provides a solution for indicating time ranges (#273).

## Documentation

- Removes references to split event-observation and media-observations tables from repo, schemas and website.
- Removes link to example pages on website, which currently don't display the correct information anymore.

**Review by kbubnicki — APPROVED** [review]

**Pull request merged**
