### PR TITLE
Platform properties grouped into one object

### PR DESCRIPTION
**Pull request by kbubnicki**

### CODE REVIEW

**Comment by peterdesmet** [comment]
@kbubnicki I rephrased some things. I also think we should drop `package_id`. If the platform assigns an ID to the package, it should go in `id` (https://specs.frictionlessdata.io/data-package/#id). It's not really a property of the `platform` anyway.

**Review by peterdesmet — CHANGES_REQUESTED** [review]
See https://github.com/tdwg/camtrap-dp/pull/146#issuecomment-866010013 I would drop `package_id`

**Comment by kbubnicki** [comment]
> If the platform assigns an ID to the package, it should go in `id` (https://specs.frictionlessdata.io/data-package/#id). It's not really a property of the `platform` anyway.

Not necessarily as `id` at the data package level can be more suited to store information about some permanent identifier (e.g. doi) linked to a data repository rather than to original platform/software that generated this package. Thinking this way, I would say, it is a property of this `platform`.

**Comment by peterdesmet** [comment]
That is true, I'm not just sure we need to store both. If a package rolls out of the platform, the `id` would be the one assigned by the platform. If the package is then published to Zenodo or elsewhere, it could be a slightly different version, with either a new `id` (e.g. the DOI) or the same one.

Do we have a use case for always wanting to be able to link to the package ID as assigned by the platform? @yliefting what do you think?

**Comment by kbubnicki** [comment]
The case could be that somebody really needs to get to the source data (stored at `platform`) to check/confirm some details about the data. Then `package_id` can be a useful information for curators/maintainers of this platform to help with such a request.

**Review by peterdesmet — APPROVED** [review]

**Comment by peterdesmet** [comment]
Fair enough, approved.

**Pull request merged**
